name: meta_trader
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # state management
  stacked: ^3.4.1

  # navigation
  auto_route: 7.8.0

  # inversion of control
  get_it: 7.2.0
  injectable: ^2.3.0

  # misc
  csslib: 0.17.0
  device_preview: 
  flutter_spinkit: 
  flutter_svg: 
  get:
  google_fonts: ^5.1.0
  intl: 
  logger: 1.1.0
  one_context: 
  provider: 
  stacked_themes: 


  persistent_bottom_nav_bar: ^5.0.2
  fade_scroll_app_bar: ^0.0.7

  date_format: ^2.0.7
  contained_tab_bar_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.9.0
  injectable_generator: ^2.4.0

  # linting
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Assets Example
  assets:
    - assets/images/
    - assets/icons/

  # Fonts Example
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Black.ttf
        - asset: fonts/Gilroy-Bold.ttf
          weight: 300
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 300
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 300
