name: meta_trader
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # state management
  stacked: ^3.4.1

  # navigation
  auto_route: 4.2.1

  # inversion of control
  get_it: 7.2.0
  injectable: 1.5.4
  
  # misc
  logger: 1.1.0
  provider:
  google_fonts: 2.2.0
  one_context:
  get:
  intl:
  device_preview:
  flutter_spinkit: 
  csslib: 0.17.0
  flutter_svg: 
  stacked_themes: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: 2.2.0
  auto_route_generator: 4.0.0
  injectable_generator: 1.5.3
  flutter_launcher_icons: ^0.9.0

  # linting
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true

# Assets Example
  assets:
    - assets/images/

# Fonts Example
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Black.ttf
        - asset: fonts/Gilroy-Bold.ttf
          weight: 300
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 300
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 300